[tox]
envlist =
    py312-test{,-devdeps}{,-cov}
    linkcheck
    codestyle
    securityaudit
    pep517
requires =
    setuptools >= 30.3.0
    pip >= 19.3.1
isolated_build = true

[testenv]
# Suppress display of matplotlib plots generated during docs build, if any
setenv =
    MPLBACKEND=agg
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/astropy/simple https://pypi.anaconda.org/scientific-python-nightly-wheels/simple

# Pass through the following environment variables which may be needed for the CI
passenv =
    HOME
    WINDIR
    LC_ALL
    LC_CTYPE
    CC
    CI

# Run tests in a temporary directory to make sure that we don't import this
# package from the source tree.
changedir = .tmp/{envname}

description =
    run tests
    devdeps: with the latest developer version of key dependencies
    cov: and test coverage

deps =
    cov: coverage
    cov: pytest-cov

    devdeps: numpy>=0.0.dev0
    devdeps: astropy>=0.0.dev0

extras =
    test

commands =
    pip freeze
    !cov: pytest --pyargs rocky_worlds_data_challenge {toxinidir}/docs {posargs}
    cov: pytest --pyargs rocky_worlds_data_challenge {toxinidir}/docs --cov rocky_worlds_data_challenge --cov-config={toxinidir}/pyproject.toml {posargs}
    cov: coverage xml -o {toxinidir}/coverage.xml

[testenv:linkcheck]
changedir = docs
description = check the links in the HTML docs
extras = docs
commands =
    pip freeze
    sphinx-build -W -b linkcheck . _build/html

[testenv:codestyle]
skip_install = true
changedir = .
description = check code style with flake8
deps = flake8
commands = flake8 rocky_worlds_data_challenge --count

[testenv:securityaudit]
skip_install = true
changedir = .
description = security audit with bandit
deps = bandit
commands = bandit -r rocky_worlds_data_challenge -x rocky_worlds_data_challenge/tests

[testenv:pep517]
skip_install = true
changedir = .
description = PEP 517
deps =
    build
    twine
commands =
    python -m build --sdist .
    twine check dist/*
